package main;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import interpreter.Interpreter;
import lexer.Lexer;
import lexer.token.Token;
import lexer.token.TokenType;
import parser.Parser;

public class Main {

	// file to be read in and parsed
	public static final File fileName = new File("source.ice");
	
	/**
	 * Reads in the file and interprets it
	 * @param args Command-line arguments
	 * @throws IOException
	 */
	public static void main(String[] args) throws IOException {
		FileReader fr = new FileReader(fileName);
		BufferedReader br = new BufferedReader(fr);
		
		String result = "";
		String read = br.readLine();
		while(read != null) {
			result += read + "\n";
			read = br.readLine();
		}
		br.close();
		
		//System.out.println(result);
		//printToken(lexer);
		
		// Data chain: Lexer -> Parser -> Interpeter
		Lexer lexer = new Lexer(result);
		Parser parser = new Parser(lexer);
		Interpreter interpreter = new Interpreter(parser);
		interpreter.interpret();
		
		// Prints variables obtained by the interpreter
		System.out.println(interpreter.variables);

	}
	
	/**
	 * Prints the tokens generated by the lexer
	 * @param lexer Lexer instance
	 */
	public static void printToken(Lexer lexer) {
		Token currentToken = lexer.getNextToken();
		while (currentToken.getType() != TokenType.T_EOF) {
			System.out.println(currentToken);
			currentToken = lexer.getNextToken();
		}
	}
}
